name: master CI/CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --save --legacy-peer-deps

      - name: Build
        run: |
          npm run build --if-present

      - name: Deploy to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTMASTER }}
          username: ${{ secrets.USERMASTER }}
          key: ${{ secrets.KEYMASTER }}
          port: ${{ secrets.PORTMASTER }}
          source: dist/
          target: /home/ubuntu/deploy/

      - name: Extract and deploy Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTMASTER }}
          username: ${{ secrets.USERMASTER }}
          key: ${{ secrets.KEYMASTER }}
          port: ${{ secrets.PORTMASTER }}
          script: |
            sudo apt-get update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
